export const categories: Category[] = [
    {
        id: '1',
        name: 'Grocery & Staples',
    },
    {
        id: '2',
        name: 'Fruits & Vegetables',
    },
    {
        id: '3',
        name: 'Beverages',
    },
    {
        id: '4',
        name: 'Noodles, Sauces & Instant Food',
    },
    {
        id: '5',
        name: 'Pet Food',
    },
    {
        id: '6',
        name: 'Personal Care',
    },
    {
        id: '7',
        name: 'Household Items',
    },
    {
        id: '8',
        name: 'Breakfast & Dairy',
    },
    {
        id: '9',
        name: 'Food & Snacks',
    },
];

export const products: Product[] = [
    {
        id: '1',
        name: 'Maggi Cheese Macaroni Instant Pasta',
        price_before_discount: '100',
        discount: '25',
        price: '75',
        quantity: '4 x 70 g',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_212784.jpg?ts=1621441886',
        category: 'Noodles, Sauces & Instant Food',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_82341.jpg',
        tags: ['Maggi', 'Pasta', 'Instant Food', 'Maggi Pasta', 'Noodles, Sauces & Instant Food'],
    },
    {
        id: '2',
        name: 'Britannia Marie Gold Biscuit, 1kg Pack',
        price_before_discount: '120',
        discount: '15',
        price: '101',
        quantity: '1 kg',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_403219.jpg?ts=1589948824',
        category: 'Food & Snacks',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_403219.jpg',
        tags: [
            'Britannia',
            'Marie Gold',
            'Biscuits',
            'Britannia Marie Gold Biscuits',
            'Biscuits, Snacks & Chocolates',
            'Food & Snacks',
        ],
    },
    {
        id: '3',
        name: 'Kissan Fresh Tomato Ketchup(Pouch) | 1L',
        price_before_discount: '120',
        discount: '15',
        price: '101',
        quantity: '1 x 1 L',
        img: 'https://m.media-amazon.com/images/I/612I6dtnY8L._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Noodles, Sauces & Instant Food',
        img_lg: 'https://m.media-amazon.com/images/I/612I6dtnY8L._SL1000_.jpg',
        tags: [
            'Ketchup',
            'Kissan Tomato Ketchup',
            'Tomato Ketchup',
            'Noodles, Sauces & Instant Food',
            'Food & Snacks',
        ],
    },
    {
        id: '4',
        name: 'Amul Taaza Toned Milk(Tetra Pack)',
        price_before_discount: '768',
        discount: '5',
        price: '733',
        quantity: '950 g',
        img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,h=280/app/images/products/normal/pro_347214.jpg',
        category: 'Breakfast & Dairy',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_347214.jpg',
        tags: ['Breakfast & Dairy', 'Milk', 'Amul Taaza', 'Toned Milk'],
    },
    {
        id: '5',
        name: "Lay's India Magic Masala Chips, 52g",
        price_before_discount: '25',
        discount: '5',
        price: '20',
        quantity: '52 g',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_240092.jpg?ts=1622013871',
        category: 'Food & Snacks',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_240092.jpg',
        tags: [
            "Lay's Chips",
            "Lays' Magic Masala Chips",
            'Magic Masala',
            'Chips',
            'Biscuits, Chips & Snacks',
            'Food & Snacks',
        ],
    },
    {
        id: '6',
        name: 'Act II Butter Delight Instant Popcorn',
        price_before_discount: '120',
        discount: '8',
        price: '110',
        quantity: '3 x 150 g',
        img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,h=280/app/images/products/normal/pro_352110.jpg',
        category: 'Food & Snacks',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_352110.jpg',
        tags: ['Act II', 'Act II Popcorn', 'Popcorn', 'Biscuits, Chips & Snacks', 'Food & Snacks'],
    },
    {
        id: '7',
        name: 'Nivea Men Dark Spot Reduction 10x Face Wash',
        price_before_discount: '199',
        discount: '24',
        price: '150',
        quantity: '100 g',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_19963.jpg?ts=1592220800',
        category: 'Personal Care',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_19963.jpg',
        tags: ['Nivea', 'Face Wash', "Nivea Men's Face Wash", "Men's Face Wash", 'Personal Care'],
    },
    {
        id: '8',
        name: 'Surf Excel Easy Wash Detergent Powder',
        price_before_discount: '440',
        discount: '21',
        price: '360',
        quantity: '4 kg',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_27070.jpg?ts=1592220800',
        category: 'Household Items',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_27070.jpg',
        tags: ['Detergent', 'Detergent Powder', 'Surf Excel', 'Household Items'],
    },
    {
        id: '9',
        name: 'Vim Lemon Dish Wash Gel (Bottle)',
        price_before_discount: '160',
        discount: '28',
        price: '115',
        quantity: '750 ml',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_11280.jpg?ts=1594380633',
        category: 'Household Items',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_11280.jpg',
        tags: ['Dish Wash Gel', 'Vim', 'Household Items'],
    },
    {
        id: '10',
        name: 'Drools Ocean Fish Cat Dry Food(Adult, +1yr year)',
        price_before_discount: '723',
        discount: '14',
        price: '723',
        quantity: '3 kg + 1.2 kg',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_430957.jpg?ts=1622626427',
        category: 'Pet Food',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_430957.jpg',
        tags: ['Cat Food', 'Pet Food', 'Cat Dry Food'],
    },
    {
        id: '11',
        name: 'Tropicana 100 Mixed Fruit Juice',
        price_before_discount: '169',
        discount: '20',
        price: '135',
        quantity: '1 x 1 L',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_375.jpg',
        category: 'Beverages',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_375.jpg',
        tags: ['Tropicana', 'Mixed Fruit', 'Tropicana Mixed Fruit Juice', 'Juices & Beverages'],
    },
    {
        id: '12',
        name: 'Nescafe Classic Coffee (Jar)',
        price_before_discount: '290',
        discount: '5',
        price: '280',
        quantity: '100 g',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_243.jpg?ts=1622799008',
        category: 'Beverages',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_243.jpg',
        tags: ['Nescafe', 'Coffee', 'Instant Coffee', 'Juices & Beverages'],
    },
    {
        id: '13',
        name: 'Fortune Chakki Fresh Atta, 10 kg',
        price_before_discount: '410',
        discount: '15',
        price: '350',
        quantity: '10 kg',
        img: 'https://m.media-amazon.com/images/I/516L7l3+ltL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Grocery & Staples',
        img_lg: 'https://m.media-amazon.com/images/I/516L7l3%2BltL.jpg',
        tags: ['Atta', 'Fortune Atta', 'Grocery & Staples'],
    },
    {
        id: '14',
        name: 'India Gate Feast Rozanna Aged Basamati Rice',
        price_before_discount: '440',
        discount: '23',
        price: '339',
        quantity: '5 kg',
        img: 'https://m.media-amazon.com/images/I/91GYB+sXpYL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Grocery & Staples',
        img_lg: 'https://m.media-amazon.com/images/I/91GYB%2BsXpYL._SX679_.jpg',
        tags: ['Rice', 'Basmati Rice', 'India Gate Rice', 'Grocery & Staples'],
    },
    {
        id: '15',
        name: 'Fortune Sunlite Refined Sunflower Oil',
        price_before_discount: '233',
        discount: '25',
        price: '174',
        quantity: '1 L',
        img: 'https://m.media-amazon.com/images/I/41Hn8WBEB7L._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Grocery & Staples',
        img_lg: 'https://m.media-amazon.com/images/I/51TH5xE%2B2sL.jpg',
        tags: ['Fortune Oil', 'Sunflower Oil', 'Cooking Oil', 'Grocery & Staples'],
    },
    {
        id: '16',
        name: 'Red Label Tea, 500 g',
        price_before_discount: '305',
        discount: '6',
        price: '285',
        quantity: '500 g',
        img: 'https://m.media-amazon.com/images/I/61+8e+4FnDL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Beverages',
        img_lg: 'https://m.media-amazon.com/images/I/618YfQ1jWeL._SX679_.jpg',
        tags: ['Tea', 'Red Label', 'Juices & Beverages'],
    },
    {
        id: '17',
        name: 'Tata Salt, 1 kg',
        price_before_discount: '20',
        discount: '10',
        price: '18',
        quantity: '1 kg',
        img: 'https://m.media-amazon.com/images/I/518GEoZtbhL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Grocery & Staples',
        img_lg: 'https://m.media-amazon.com/images/I/518GEoZtbhL.jpg',
        tags: ['Salt', 'Tata Salt', 'Grocery & Staples'],
    },
    {
        id: '18',
        name: 'Apis Himalaya Honey - Buy 1 Get 1 Free -',
        price_before_discount: '440',
        discount: '9',
        price: '398',
        quantity: '2 x 1 kg',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_247449.jpg?ts=1608806418',
        category: 'Breakfast & Dairy',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_247449.jpg',
        tags: ['Honey', 'Apis Honey', 'Breakfast & Dairy'],
    },
    {
        id: '19',
        name: "Kelogg's Crunchy Granola Almonds And Cranberries | Multigrain Flakes, 460g",
        price_before_discount: '430',
        discount: '20',
        price: '342',
        quantity: '460 g',
        img: 'https://m.media-amazon.com/images/I/61iGpCQrr1L._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Breakfast & Dairy',
        img_lg: 'https://m.media-amazon.com/images/I/61iGpCQrr1L._SX679_.jpg',
        tags: ['Cereals', 'Cornflakes', "Kellogg's", 'Kellogs Almonds And Cranberries'],
    },
    {
        id: '20',
        name: 'Quaker Oats - 1 kg',
        price_before_discount: '195',
        discount: '13',
        price: '169',
        quantity: '1 kg',
        img: 'https://m.media-amazon.com/images/I/71Yy6rdycDL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Breakfast & Dairy',
        img_lg: 'https://m.media-amazon.com/images/I/71vjyTjbpoL._SX679_.jpg',
        tags: ['Oats', 'Quaker Oats', 'Breakfast & Dairy'],
    },
    {
        id: '21',
        name: 'Oreo Original Vanilla Creme Biscuit - Pack of 3',
        price_before_discount: '90',
        discount: '13',
        price: '78',
        quantity: '3 x 120 g',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_369175.jpg?ts=1621853803',
        category: 'Food & Snacks',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_369175.jpg',
        tags: [
            'Oreo',
            'Oreo Original',
            'Biscuits',
            'Biscuits, Snacks & Chocolates',
            'Food & Snacks',
        ],
    },
    {
        id: '22',
        name: 'Oreo Choco Creme Biscuit - Pack of 3',
        price_before_discount: '90',
        discount: '13',
        price: '78',
        quantity: '3 x 120 g',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_369174.jpg?ts=1621853803',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_369174.jpg',
        category: 'Food & Snacks',
        tags: [
            'Oreo',
            'Oreo Chocolate',
            'Biscuits',
            'Biscuits, Snacks & Chocolates',
            'Food & Snacks',
        ],
    },
    {
        id: '23',
        name: 'Harpic Disinfectant Toilet Cleaner Liquid',
        price_before_discount: '320',
        discount: '3',
        price: '310',
        quantity: '2 x 1 L',
        img: 'https://m.media-amazon.com/images/I/61z8h3l3DvL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Household Items',
        img_lg: 'https://m.media-amazon.com/images/I/61z8h3l3DvL._SL1000_.jpg',
        tags: ['Harpic', 'Toilet Cleaner Liquid', 'Disinfectants', 'Household Items'],
    },
    {
        id: '24',
        name: 'Doritos Nachos Chips - Sweet Chilli Flavor',
        price_before_discount: '50',
        discount: '10',
        price: '45',
        quantity: '110 g',
        img: 'https://m.media-amazon.com/images/I/712gvKYX2fL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Food & Snacks',
        img_lg: 'https://m.media-amazon.com/images/I/712gvKYX2fL._SL1500_.jpg',
        tags: ['Doritos', 'Nachos', 'Chips', 'Biscuits, Chips & Snacks', 'Food & Snacks'],
    },
    {
        id: '25',
        name: 'Flavors of Calicut - Kerala Banana Chips',
        price_before_discount: '399',
        discount: '13',
        price: '349',
        quantity: '500 g',
        img: 'https://m.media-amazon.com/images/I/61lCDF2ZsZS._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Food & Snacks',
        img_lg: 'https://m.media-amazon.com/images/I/61lCDF2ZsZS._SL1200_.jpg',
        tags: [
            'Banana Chips',
            'Kerala Chips',
            'Chips',
            'Biscuits, Chips & Snacks',
            'Food & Snacks',
        ],
    },
    {
        id: '26',
        name: 'Bingo Mad Angles - Achaari Masti',
        price_before_discount: '25',
        discount: '5',
        price: '20',
        quantity: '75 g',
        img: 'https://m.media-amazon.com/images/I/814gWY+drSL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Food & Snacks',
        img_lg: 'https://m.media-amazon.com/images/I/814gWY%2BdrSL._SL1500_.jpg',
        tags: [
            'Bingo Chips',
            'Achaari Masti Chips',
            'Chips',
            'Biscuits, Chips & Snacks',
            'Food & Snacks',
        ],
    },
    {
        id: '27',
        name: 'Lifebuoy Liquid Handwash Refill',
        price_before_discount: '210',
        discount: '10',
        price: '189',
        quantity: '2 x 750 ml',
        img: 'https://m.media-amazon.com/images/I/61Ef+QnNkxS._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Household Items',
        img_lg: 'https://m.media-amazon.com/images/I/61Ef%2BQnNkxS._SL1000_.jpg',
        tags: ['Lifebuoy', 'Lifebuoy Handwash', 'Handwash Refill', 'Household Items'],
    },
    {
        id: '28',
        name: 'Lizol Disenfectant Surface & Floor Cleaner Liquid',
        price_before_discount: '98',
        discount: '19',
        price: '78',
        quantity: '500 ml',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_59843.jpg?ts=1620894067',
        category: 'Household Items',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_59843.jpg',
        tags: ['Lizol', 'Floor Cleaner Liquid', 'Disinfectants', 'Household Items'],
    },
    {
        id: '29',
        name: 'Fresh Pomogrenate, 4 Pcs',
        price_before_discount: '267',
        discount: '47',
        price: '141',
        quantity: '4 pcs',
        img: 'https://m.media-amazon.com/images/I/818gPzn-9sL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Fruits & Vegetables',
        img_lg: 'https://m.media-amazon.com/images/I/818gPzn-9sL._AC_UL480_FMwebp_QL65_.jpg',
        tags: ['Fruits & Vegetables', 'Fruits', 'Pomogrenate'],
    },
    {
        id: '30',
        name: 'Fresh Watermelon, 1 Pc',
        price_before_discount: '78',
        discount: '46',
        price: '42',
        quantity: '1 pc',
        img: 'https://m.media-amazon.com/images/I/71ZaS7W9dYL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Fruits & Vegetables',
        img_lg: 'https://m.media-amazon.com/images/I/71ZaS7W9dYL._SL1500_.jpg',
        tags: ['Fruits & Vegetables', 'Fruits', 'Watermelon'],
    },
    {
        id: '31',
        name: 'Fresh Pear Green Imported, 4 Pcs',
        price_before_discount: '299',
        discount: '62',
        price: '113',
        quantity: '4 pcs',
        img: 'https://m.media-amazon.com/images/I/81WnPYsrozL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Fruits & Vegetables',
        img_lg: 'https://m.media-amazon.com/images/I/81WnPYsrozL._SL1500_.jpg',
        tags: ['Fruits & Vegetables', 'Fruits', 'Pear'],
    },
    {
        id: '32',
        name: 'Fresh Potatoes, 1 kg',
        price_before_discount: '79',
        discount: '78',
        price: '17',
        quantity: '',
        img: 'https://m.media-amazon.com/images/I/61yXL70-RaL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Fruits & Vegetables',
        img_lg: 'https://m.media-amazon.com/images/I/617yrpyUYWL._SL1500_.jpg',
        tags: ['Fruits & Vegetables', 'Vegetables', 'Potatoes'],
    },
    {
        id: '33',
        name: 'Nescafe Classic Instant Coffee, 200 g',
        price_before_discount: '500',
        discount: '5',
        price: '475',
        quantity: '200 g',
        img: 'https://m.media-amazon.com/images/I/71zjeDcWWXL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Beverages',
        img_lg: 'https://m.media-amazon.com/images/I/71zjeDcWWXL._SX679_.jpg',
        tags: ['Nescafe', 'Coffee', 'Instant Coffee', 'Juices & Beverages'],
    },
    {
        id: '34',
        name: 'Dettol Original Germ Protection Soap Bar 125 g, Buy 4 Get 1 Free',
        price_before_discount: '219',
        discount: '6',
        price: '204',
        quantity: '4 x 125 g',
        img: 'https://m.media-amazon.com/images/I/61R9Fg4UGmL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/61R9Fg4UGmL._SL1000_.jpg',
        tags: ['Dettol', 'Dettol Soap', 'Soap', 'Personal Care'],
    },
    {
        id: '35',
        name: 'Dove Creme Beauty Bar - Soap | Pack of 3',
        price_before_discount: '209',
        discount: '9',
        price: '189',
        quantity: '3 x 125 g',
        img: 'https://m.media-amazon.com/images/I/61nF1U8dpbL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_445815.jpg',
        tags: ['Dove', 'Dove Soap', 'Soap', 'Personal Care'],
    },
    {
        id: '36',
        name: 'Whisper Ultra Night Sanitary Pads For Women, X-Large | Pack of 50 Napkins',
        price_before_discount: '520',
        discount: '34',
        price: '341',
        quantity: '50 napkins',
        img: 'https://m.media-amazon.com/images/I/8111GMZdUwL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/8111GMZdUwL._SL1500_.jpg',
        tags: ['Sanitary Napkins', 'Whisper Ultra', 'Pads', 'Personal Care'],
    },
    {
        id: '37',
        name: "Nivea Men's Deodorant, 150 ml",
        price_before_discount: '199',
        discount: '25',
        price: '149',
        quantity: '150 ml',
        img: 'https://m.media-amazon.com/images/I/71KKYecRpiL._SY355_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/71Bz5isk23L._SX679_.jpg',
        tags: ['Nivea', "Nivea Men's Deodorant", 'Deodorant', 'Personal Care'],
    },
    {
        id: '38',
        name: 'Pedigree Adult Dry Dog Food, Chicken & Vegetables, 3kg Pack',
        price_before_discount: '600',
        discount: '10',
        price: '542',
        quantity: '3 kg',
        img: 'https://m.media-amazon.com/images/I/61Aqqe8HgjL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Pet Food',
        img_lg: 'https://m.media-amazon.com/images/I/61ZdlkTdMrL._SX679_.jpg',
        tags: ['Pet Food', 'Dog Food', 'Pedigree Dog Food', 'Dry Dog Food'],
    },
    {
        id: '39',
        name: "Kelogg's Cornflakes Original | 875g Pack",
        price_before_discount: '290',
        discount: '7',
        price: '270',
        quantity: '1 x 875 g',
        img: 'https://m.media-amazon.com/images/I/71cqU2ZyPNL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Breakfast & Dairy',
        img_lg: 'https://m.media-amazon.com/images/I/71HsQr-pYjL._SL1500_.jpg',
        tags: ['Cereals', 'Cornflakes', "Kellogg's", 'Kellogs Original'],
    },
    {
        id: '40',
        name: 'Whiskas Kitten (2-12 Months) Dry Cat Food, Ocean Fish, 480g Pack',
        price_before_discount: '185',
        discount: '5',
        price: '175',
        quantity: '1 x 480 g',
        img: 'https://m.media-amazon.com/images/I/61unmH6bowL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Pet Food',
        img_lg: 'https://m.media-amazon.com/images/I/81VMdn7i0cL._SL1500_.jpg',
        tags: ['Pet Food', 'Cat Food', 'Dry Cat Food'],
    },
    {
        id: '41',
        name: 'Sensodyne Toothpaste | 100 gm',
        price_before_discount: '210',
        discount: '9',
        price: '190',
        quantity: '100 gm',
        img: 'https://m.media-amazon.com/images/I/51q7XZVROxL._AC._SR360,460.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/51q7XZVROxL._SL1000_.jpg',
        tags: ['Sensodyne', 'Toothpaste', 'Personal Care'],
    },
    {
        id: '42',
        name: 'Oral B Pro Toothbrush | Pack of 4',
        price_before_discount: '160',
        discount: '6',
        price: '150',
        quantity: '4 x 1',
        img: 'https://m.media-amazon.com/images/I/71tCmWHvOyL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/71jVVULonsL._SL1500_.jpg',
        tags: ['Oral B', 'Toothbrush', 'Personal Care'],
    },
    {
        id: '43',
        name: "Nivea Women's Deodorant, 150 ml ",
        price_before_discount: '190',
        discount: '6',
        price: '179',
        quantity: '150 ml',
        img: 'https://m.media-amazon.com/images/I/71xQ85tzqLL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/71sTe32JlpL._SL1500_.jpg',
        tags: ['Nivea', "Nivea Women's Deodorant", 'Deodorant', 'Personal Care'],
    },
    {
        id: '44',
        name: 'HIT Cocroach Killer Spray, 700 ml',
        price_before_discount: '325',
        discount: '10',
        price: '293',
        quantity: '700 ml',
        img: 'https://m.media-amazon.com/images/I/71UYTPMwiEL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Household Items',
        img_lg: 'https://m.media-amazon.com/images/I/71UYTPMwiEL._SL1500_.jpg',
        tags: ['Hit Spray', 'Cockroach Spray', 'Household Items'],
    },
    {
        id: '45',
        name: 'All Out Ultra - Mosquito Repellent (Refill) - Pack of 6',
        price_before_discount: '390',
        discount: '15',
        price: '328',
        quantity: '6 x 45',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_254556.jpg?ts=1581936485',
        category: 'Household Items',
        img_lg: 'https://m.media-amazon.com/images/I/61Vj9w5RNoL._SL1000_.jpg',
        tags: ['Mosquito Repellent', 'All Out', 'Household Items'],
    },
    {
        id: '46',
        name: 'Dettol Original Germ Protection Hand Sanitizer',
        price_before_discount: '250',
        discount: '20',
        price: '200',
        quantity: '500 ml',
        img: 'https://m.media-amazon.com/images/I/51v4rFT8TNL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/51yfKqpz7xL._SL1000_.jpg',
        tags: ['Dettol', 'Hand Sanitizer', 'Personal Care'],
    },
    {
        id: '47',
        name: 'Maggi 2-Minute Instant Noodles Masala, 700g, Pack of 12',
        price_before_discount: '144',
        discount: '7',
        price: '134',
        quantity: '12 x 700 g',
        img: 'https://m.media-amazon.com/images/I/81tiRzUBKEL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Noodles, Sauces & Instant Food',
        img_lg: 'https://m.media-amazon.com/images/I/81WyWDbuqsL._SL1500_.jpg',
        tags: ['Maggi', 'Instant Noodles', 'Instant Food', 'Noodles, Sauces & Instant Food'],
    },
    {
        id: '48',
        name: 'Top Ramen Chicken Noodles',
        price_before_discount: '60',
        discount: '7',
        price: '56',
        quantity: '1 x 280 g',
        img: 'https://m.media-amazon.com/images/I/91ySC73lgfL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Noodles, Sauces & Instant Food',
        img_lg: 'https://m.media-amazon.com/images/I/91ySC73lgfL._SL1500_.jpg',
        tags: ['Top Ramen', 'Instant Noodles', 'Instant Foood', 'Noodles, Sauces & Instant Food'],
    },
    {
        id: '49',
        name: 'Nestle Everyday Dairy Whitener, Milk Powder for Tea, 1 kg Pouch',
        price_before_discount: '490',
        discount: '4',
        price: '470',
        quantity: '1kg',
        img: 'https://m.media-amazon.com/images/I/71RnaL8uLKL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Beverages',
        img_lg: 'https://m.media-amazon.com/images/I/71RnaL8uLKL._SL1500_.jpg',
        tags: ['Nestle', 'Milk Powder', 'Beverages'],
    },
    {
        id: '50',
        name: 'Pepsi Black Slim Soft Drink (Can) - Buy 4 Get 2 Free',
        price_before_discount: '180',
        discount: '33',
        price: '120',
        quantity: '6x250 ml',
        img: 'https://cdn.grofers.com/app/images/products/normal/pro_391246.jpg?ts=1620286317',
        category: 'Beverages',
        img_lg: 'https://cdn.grofers.com/app/images/products/full_screen/pro_391246.jpg',
        tags: ['Pepsi', 'Juices & Beverages', 'Pepsi Black', 'Diet Coke', 'Beverages'],
    },
    {
        id: '51',
        name: 'Cadbury Dairy Milk Chocolate Shots, 208 g Carton',
        price_before_discount: '112',
        discount: '13',
        price: '98',
        quantity: '58 units x 3.6 g',
        img: 'https://m.media-amazon.com/images/I/71mLCMSiJ9L._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Food & Snacks',
        img_lg: 'https://m.media-amazon.com/images/I/71mLCMSiJ9L._SX679_.jpg',
        tags: ['Chocolate', 'Cadbury Shots', 'Food & Snacks', 'Biscuits, Snacks & Chocolates'],
    },
    {
        id: '52',
        name: 'Tresemme Keratin Smooth Shampoo, 1 Ltr',
        price_before_discount: '750',
        discount: '25',
        price: '560',
        quantity: '1 x 1 L',
        img: 'https://m.media-amazon.com/images/I/51d+8aYUDTL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Personal Care',
        img_lg: 'https://m.media-amazon.com/images/I/51d+8aYUDTL._SL1000_.jpg',
        tags: ['Shampoo', 'Tresemme', 'Personal Care'],
    },
    {
        id: '53',
        name: 'Solimo Toilet Paper - 12 Rolls',
        price_before_discount: '350',
        discount: '17',
        price: '289',
        quantity: '12 x 1 Rolls',
        img: 'https://m.media-amazon.com/images/I/71m-Gpu0spL._AC_UL480_FMwebp_QL65_.jpg',
        category: 'Household Items',
        img_lg: 'https://m.media-amazon.com/images/I/71m-Gpu0spL._AC_UL480_FMwebp_QL65_.jpg',
        tags: ['Household Items', 'Toilet Paper'],
    },
    {
        id: '54',
        name: 'Samyang Hot Chicken Ramen Cheese Noodles, 5 x 140 g',
        price_before_discount: '625',
        discount: '20',
        price: '499',
        quantity: '5 x 140g',
        img: 'https://m.media-amazon.com/images/I/71-FhSJVzlL._AC_UL480_FMwebp_QL65_.jpg',
        img_lg: 'https://m.media-amazon.com/images/I/71-FhSJVzlL._SL1024_.jpg',
        category: 'Noodles, Sauces & Instant Food',
        tags: ['Ramen', 'Instant Noodles', 'Instant Foood', 'Noodles, Sauces & Instant Food'],
    },
];
