import { useContext } from 'react';
import Link from 'next/link';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/navbar';
import { AuthContext } from '../context/AuthContext';
import { CartContext } from '../context/CartContext';
import { products } from '../products.dummy';
import BottomNavbar from '../components/bottomNavbar';

const Cart: NextPage = () => {
    const { authLoading, isAuth } = useContext(AuthContext);
    const { cart, cartLoading } = useContext(CartContext);
    let cartData = cart?.map((item: Order) => ({
        ...products[parseInt(item.product_id) - 1],
        items: item.qty,
    }));
    let totalAmt = 0;
    if (cartData) {
        for (let item of cartData) {
            totalAmt += parseInt(item.price) * item.items;
        }
    }

    return (
        <div>
            <Head>
                <title>Grocery App: Your Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative flex flex-col mt-20 mb-20 sm:mb-0">
                <Navbar />
                <main className="max-w-full px-6">
                    {authLoading || cartLoading ? (
                        <div className="flex justify-center items-center mt-20 pt-20">
                            <div className="h-2.5 w-2.5 bg-yellow-600 rounded-full mr-1 animate-bounce"></div>
                            <div className="h-2.5 w-2.5 bg-yellow-600 rounded-full mr-1 animate-bounce200"></div>
                            <div className="h-2.5 w-2.5 bg-yellow-600 rounded-full animate-bounce400"></div>
                        </div>
                    ) : !cart || cart.length === 0 ? (
                        <div className="flex flex-col justify-center items-center">
                            <Image
                                alt="Empty Cart"
                                width={400}
                                height={400}
                                src="/assets/cart_empty.png"
                            />
                            <div className="mt-3 mb-4 text-center">
                                <h4 className="text-black text-xl font-semibold pb-1">
                                    Your bag is empty :(
                                </h4>
                                <p className="text-gray-600">
                                    You dont have any products in your cart.
                                </p>
                            </div>
                            <div>
                                <Link href="/" passHref>
                                    <button className="py-1 px-2 border border-yellow-600 text-yellow-600 uppercase hover:text-white hover:bg-yellow-600 rounded-full w-64 focus:outline-none">
                                        Continue shopping
                                    </button>
                                </Link>
                            </div>
                            {!isAuth && (
                                <div className="mt-2 pb-2">
                                    <Link href="/login" passHref>
                                        <button className="py-1 px-2 border border-gray-600 text-gray-600 uppercase hover:text-white hover:bg-gray-600 rounded-full w-64 focus:outline-none">
                                            Log in
                                        </button>
                                    </Link>
                                </div>
                            )}
                        </div>
                    ) : (
                        <div className="pb-10">
                            <div className="pt-6">
                                <div className="text-sm flex text-yellow-600">
                                    <Link href="/" passHref>
                                        Home
                                    </Link>
                                    <div className="pl-2">{`>`}</div>
                                    <div className="pl-2 text-gray-600">Your Bag</div>
                                </div>
                                <h3 className="text-lg sm:text-2xl pt-6 pb-2 font-semibold">
                                    Your Bag
                                </h3>
                                <div className="flex text-sm sm:text-base text-gray-600 pb-4">
                                    Subtotal ({cart.length} items) :
                                    <div className="text-black font-bold pl-2">
                                        ₹{totalAmt.toLocaleString('en-IN')}
                                    </div>
                                </div>
                            </div>
                            <div className="sm:px-6 max-w-full pt-4">
                                {cartData?.map((item: Product, idx: number) => {
                                    return (
                                        <div key={idx}>
                                            <div className="px-4 py-2 bg-white border border-gray-300">
                                                <div className="flex flex-col sm:flex-row justify-between items-center">
                                                    <div className="flex justify-start items-center">
                                                        <div className="pr-8 sm:pr-2 mr-2">
                                                            <Link
                                                                href={`/category/${item.category}/${item.id}`}
                                                                passHref
                                                            >
                                                                <Image
                                                                    alt={item.name}
                                                                    height={125}
                                                                    width={125}
                                                                    src={item.img_lg}
                                                                    objectFit='cover'
                                                                />
                                                                {/* <img
                                                                    alt={item.name}
                                                                    className="h-24 w-16 sm:h-32 sm:w-32 object-cover"
                                                                    src={item.img_lg}
                                                                /> */}
                                                            </Link>
                                                        </div>
                                                        <div className="block sm:hidden flex-1 flex-col sm:flex-row">
                                                            <Link
                                                                href={`/category/${item.category}/${item.id}`}
                                                                passHref
                                                            >
                                                                <div
                                                                    style={{ flex: '0 0 100%' }}
                                                                    className="text-sm sm:text-lg max-w-full pr-8"
                                                                >
                                                                    {item.name}
                                                                </div>
                                                            </Link>
                                                            <div className="text-xs font-bold text-yellow-600 pt-2">
                                                                Qty: {item.items}
                                                            </div>
                                                        </div>
                                                        <div className="flex-0 pl-6 text-sm text-black font-bold sm:flex-none sm:hidden">
                                                            ₹{parseInt(item.price) * item.items!}
                                                        </div>
                                                        <div className="flex flex-col hidden sm:block">
                                                            <div className="hidden sm:block text-sm sm:text-lg">
                                                                {item.name}
                                                            </div>
                                                            <div className="pt-2 text-sm text-yellow-600 font-bold">
                                                                Qty: {item.items}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="hidden sm:block font-bold text-sm sm:text-lg pl-4">
                                                        ₹{item.price}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    )}
                </main>
                <BottomNavbar />
            </div>
        </div>
    );
};

export default Cart;
