import { useContext } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Error from './_error';
import Image from 'next/image';
import Navbar from '../components/navbar';
import BottomNavbar from '../components/bottomNavbar';
import BrowseCategories from '../components/browseCategories';
import TopCategories from '../components/topCategories';
import TopProducts from '../components/topProducts';
import { AuthContext } from '../context/AuthContext';
import { CartContext } from '../context/CartContext';

const Home: NextPage = () => {
    const { authLoading, error } = useContext(AuthContext);
    const { cartLoading } = useContext(CartContext);

    if (error) {
        return <Error statusCode={500} />;
    }

    return (
        <div>
            <Head>
                <title>Next Grocery App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {authLoading || cartLoading ? (
                <div className="relative bg-gray-100">
                    <Navbar />
                    <div className="flex justify-center items-center mt-20 pt-20">
                        <div className="h-2.5 w-2.5 bg-yellow-600 rounded-full mr-1 animate-bounce"></div>
                        <div className="h-2.5 w-2.5 bg-yellow-600 rounded-full mr-1 animate-bounce200"></div>
                        <div className="h-2.5 w-2.5 bg-yellow-600 rounded-full animate-bounce400"></div>
                    </div>
                    <BottomNavbar />
                </div>
            ) : (
                <div className="relative bg-gray-100 mt-20 mb-20">
                    <Navbar />
                    <main>
                        <TopCategories />
                        <BrowseCategories />
                        <TopProducts />
                        <BottomNavbar />
                    </main>
                </div>
            )}
        </div>
    );
};

export default Home;
